# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: debug-statements
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.260'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

# Add this to your .pre-commit-config.yaml file
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version available
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-builtins
          - flake8-comprehensions

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, pydantic]
        exclude: ^(tests/|docs/)
